apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-mysql
  labels:
    app: example-app
    name: simple-webapp-mysql
spec:
  containers:
  - name: simple-webapp-mysql
    image: 174494357773.dkr.ecr.us-east-1.amazonaws.com/simple_webapp_mysql
    ports:
    - containerPort: 81
    envFrom:
      - secretRef:
          name: app-secret
      - configMapRef:
          name: swbapp-config

